services:
  backend:
    build: .
    restart: always
    ports:
      - '8000:80'
    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy
        restart: true

    command:
      - fastapi
      - --reload

    volumes:
      - ./app:/app/app

  postgres:
    image: postgres:16
    restart: always
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - '5433:5432'
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME?Variable not set}
      - POSTGRES_PASSWORD=${DB_PASSWORD?Variable not set}
      - POSTGRES_DB=${DB_DATABASE?Variable not set}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
